version: "3.9"
services:
  manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - node-manager-data:/data
networks:
  default:
volumes:
  node-manager-data: